// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.2
// source: primes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimesRequest) Reset() {
	*x = PrimesRequest{}
	mi := &file_primes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimesRequest) ProtoMessage() {}

func (x *PrimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_primes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimesRequest.ProtoReflect.Descriptor instead.
func (*PrimesRequest) Descriptor() ([]byte, []int) {
	return file_primes_proto_rawDescGZIP(), []int{0}
}

func (x *PrimesRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PrimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimesResponse) Reset() {
	*x = PrimesResponse{}
	mi := &file_primes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimesResponse) ProtoMessage() {}

func (x *PrimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_primes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimesResponse.ProtoReflect.Descriptor instead.
func (*PrimesResponse) Descriptor() ([]byte, []int) {
	return file_primes_proto_rawDescGZIP(), []int{1}
}

func (x *PrimesResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_primes_proto protoreflect.FileDescriptor

const file_primes_proto_rawDesc = "" +
	"\n" +
	"\fprimes.proto\x12\n" +
	"calculator\"'\n" +
	"\rPrimesRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\"(\n" +
	"\x0ePrimesResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06resultB4Z2github.com/trangluongdoi2/my-grpc/calculator/protob\x06proto3"

var (
	file_primes_proto_rawDescOnce sync.Once
	file_primes_proto_rawDescData []byte
)

func file_primes_proto_rawDescGZIP() []byte {
	file_primes_proto_rawDescOnce.Do(func() {
		file_primes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_primes_proto_rawDesc), len(file_primes_proto_rawDesc)))
	})
	return file_primes_proto_rawDescData
}

var file_primes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_primes_proto_goTypes = []any{
	(*PrimesRequest)(nil),  // 0: calculator.PrimesRequest
	(*PrimesResponse)(nil), // 1: calculator.PrimesResponse
}
var file_primes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_primes_proto_init() }
func file_primes_proto_init() {
	if File_primes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_primes_proto_rawDesc), len(file_primes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_primes_proto_goTypes,
		DependencyIndexes: file_primes_proto_depIdxs,
		MessageInfos:      file_primes_proto_msgTypes,
	}.Build()
	File_primes_proto = out.File
	file_primes_proto_goTypes = nil
	file_primes_proto_depIdxs = nil
}
